### ISSUE TITLE
Views not respecting embargo

### ISSUE THREAD

**Issue by seth-shaw-unlv** [discoverygarden/embargoes#16]
I took an Islandora 1.1.0 image and created a collection with two items:
<img width="729" alt="Screen Shot 2021-02-05 at 2 55 17 PM" src="https://user-images.githubusercontent.com/29869988/107097865-cae12080-67c2-11eb-8deb-e8ea0bcf8e28.png">

I then embargoed one of the collection members: "Item One, to be embargoed":
<img width="1006" alt="Screen Shot 2021-02-05 at 2 56 19 PM" src="https://user-images.githubusercontent.com/29869988/107097924-e6e4c200-67c2-11eb-9dce-342a1f86dad8.png">

I then opened an incognito window to view the collection:
<img width="832" alt="Screen Shot 2021-02-05 at 2 56 59 PM" src="https://user-images.githubusercontent.com/29869988/107097979-fb28bf00-67c2-11eb-9ca5-7412d3731c44.png">

Notice that it gives a some-what misleading message, because it seems to indicate the collection is under embargo, while only one object in the collection actually is. (Side-note: so we should probably use the node's title instead of "This resource".) You will also see that the teaser of the embargoed node is still shown in the members view.

Clicking on the embargoed node's link *does* direct us to an "access denied" page; although the node shouldn't have appeared in the first place:
<img width="446" alt="Screen Shot 2021-02-05 at 2 57 25 PM" src="https://user-images.githubusercontent.com/29869988/107098174-78543400-67c3-11eb-83df-3249f63db60e.png">

**Comment by seth-shaw-unlv** [comment]
Clearing cache doesn't help. 

I also checked the node_access table and the embargoed item isn't included:
```
mysql> select * from node_access;
+-----+----------+----------+-----+-------+------------+--------------+--------------+
| nid | langcode | fallback | gid | realm | grant_view | grant_update | grant_delete |
+-----+----------+----------+-----+-------+------------+--------------+--------------+
|   0 |          |        1 |   0 | all   |          1 |            0 |            0 |
+-----+----------+----------+-----+-------+------------+--------------+--------------+
1 row in set (0.00 sec)
```

Ah! from the [Drupal API documentation for function hook_ENTITY_TYPE_access](https://api.drupal.org/api/drupal/core%21lib%21Drupal%21Core%21Entity%21entity.api.php/function/hook_ENTITY_TYPE_access/8.9.x):

> Note that this hook is not called for listings (e.g., from entity queries and Views). For nodes, see Node access rights for a full explanation. For other entity types, see hook_query_TAG_alter().

**Comment by jordandukart** [comment]
Fixed in https://github.com/discoverygarden/embargoes/pull/24.
